### ISSUE TITLE
Cadastrar usuário

### ISSUE THREAD

**Issue by CauaMatheus** [UnBArqDsw2024-1/2024.1_G10_My_Lyrics#2]
# Introdução
Para o sistema funcionar como um todo, é crucial que novos usuários consigam se cadastrar no nosso sistema. Essa criação será criada por uma tela de registro

# Desenvolvimento
![Image](https://github.com/user-attachments/assets/2eac8010-7d04-4a84-beac-97ee37947f39)

Pelo protótipo, será necessário apenas o email e a senha para se registrar. Logo, o payload da request deve ser:
## `POST` /users
```json
{
    "name": "string",
    "email": "string",
    "password": "string",
    "confirmedPassword": "string"
}
```

# Banco de dados
A estrutura do banco de dados pode ser vista no DE-R e DLD presentes na documentação

# Critérios de aceitação
- [ ] A senha deve ser salva criptografada
- [ ] A senha deve ter pelo menos 6 caracteres
- [ ] O email não pode repetir no banco de dados

**Comment by SamuelRicardoDS** [comment]
create user working as expected!
